# Generated by Django 4.1.3 on 2022-11-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_email',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name=''),
        ),
    ]
