# Generated by Django 4.1.2 on 2022-11-06 14:24

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_user_email_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=254, verbose_name='')),
        ),
    ]
