# Generated by Django 4.1.2 on 2022-11-04 11:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_otpmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmaster',
            name='value',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='')),
        ),
    ]
