# Generated by Django 4.1.3 on 2022-11-11 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name=''),
            preserve_default=False,
        ),
    ]
